services:
    mealsquare.type.ingredient:
        class: MealSquare\RecetteBundle\Form\IngredientRecetteType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: ingredient_recette_type }

    sonata.block.service.recipe:
        class: MealSquare\RecetteBundle\Block\RecentRecipesBlockService
        arguments: [ "sonata.block.service.user",@templating , @doctrine.orm.entity_manager ]
        tags:
            - { name: sonata.block }

