meal_square_common_homepage:
    path:     /
    defaults: { _controller: MealSquareCommonBundle:Default:index }
    
meal_square_common_message:
    path:     /message
    defaults: { _controller: MealSquareCommonBundle:Message:index }

meal_square_common_setlocale:
    path: /setlocale/{language}
    defaults: {_controller: MealSquareCommonBundle:Locale:setlocale}
