services:
  # mealsquare.common.locale_listener:
  #     class: MealSquare\CommonBundle\EventListener\LocaleListener
  #     arguments: ["%kernel.default_locale%"]
  #     tags:
  #         - { name: kernel.event_subscriber }