services:
    sonata.user.admin.badge:
        class: Application\Sonata\UserBundle\Admin\BadgeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Utilisateur", label: "Badge" }
        arguments:
            - ~
            - Application\Sonata\UserBundle\Entity\Badge
            - ~
        calls:
            - [ setTranslationDomain, [ApplicationSonataUserBundle]]

    sonata.block.service.user:
        class: Application\Sonata\UserBundle\Block\RecentUsersBlockService
        arguments: [ "sonata.block.service.user",@templating , @doctrine.orm.entity_manager ]
        tags:
            - { name: sonata.block }